# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-09 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuip', models.CharField(max_length=15)),
                ('tipodoc', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('Nit', 'Nit'), ('CE', 'Cedula de Extranjeria')], max_length=1)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('A', 'Automovil - Camioneta - Campero'), ('C', 'Camion'), ('M', 'Moto'), ('P', 'De Carga'), ('Q', 'Cuatrimoto'), ('H', 'Ciclo Motor')], max_length=1)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.IntegerField(default=0)),
                ('cilindraje', models.IntegerField(default=0)),
                ('tipo_servicio', models.CharField(choices=[('R', 'Particular'), ('P', 'Publico'), ('O', 'Oficial')], max_length=1)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.Propietarios')),
            ],
        ),
    ]
