# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-09 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietarios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='id',
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='nuip',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
