# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_auto_20180909_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarios',
            name='tipodoc',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('NIT', 'Nit'), ('CE', 'Cedula de Extranjeria')], max_length=3),
        ),
    ]
